/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentResponse {
    #[serde(rename = "public_url", skip_serializing_if = "Option::is_none")]
    pub public_url: Option<String>,
}

impl DocumentResponse {
    pub fn new() -> DocumentResponse {
        DocumentResponse {
            public_url: None,
        }
    }
}


