/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentsResponseModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "viewed_first_at", skip_serializing_if = "Option::is_none")]
    pub viewed_first_at: Option<String>,
    #[serde(rename = "viewed_last_at", skip_serializing_if = "Option::is_none")]
    pub viewed_last_at: Option<String>,
}

impl DocumentsResponseModel {
    pub fn new(id: String, name: String, created_at: String, category: String, link: String) -> DocumentsResponseModel {
        DocumentsResponseModel {
            id,
            name,
            created_at,
            category,
            link,
            viewed_first_at: None,
            viewed_last_at: None,
        }
    }
}


