/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUserResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "firstname", skip_serializing_if = "Option::is_none")]
    pub firstname: Option<String>,
    #[serde(rename = "lastname", skip_serializing_if = "Option::is_none")]
    pub lastname: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "phone_verified", skip_serializing_if = "Option::is_none")]
    pub phone_verified: Option<String>,
    #[serde(rename = "pin_verified")]
    pub pin_verified: bool,
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "trading_plan")]
    pub trading_plan: String,
    #[serde(rename = "data_plan")]
    pub data_plan: String,
    #[serde(rename = "tax_allowance", skip_serializing_if = "Option::is_none")]
    pub tax_allowance: Option<i32>,
    #[serde(rename = "tax_allowance_start", skip_serializing_if = "Option::is_none")]
    pub tax_allowance_start: Option<String>,
    #[serde(rename = "tax_allowance_end", skip_serializing_if = "Option::is_none")]
    pub tax_allowance_end: Option<String>,
    #[serde(rename = "optin_order_push")]
    pub optin_order_push: bool,
    #[serde(rename = "optin_order_email")]
    pub optin_order_email: bool,
    #[serde(rename = "country")]
    pub country: String,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
}

impl GetUserResponse {
    pub fn new(created_at: String, user_id: String, pin_verified: bool, account_id: String, trading_plan: String, data_plan: String, optin_order_push: bool, optin_order_email: bool, country: String, language: String, timezone: String) -> GetUserResponse {
        GetUserResponse {
            created_at,
            user_id,
            firstname: None,
            lastname: None,
            email: None,
            phone: None,
            phone_verified: None,
            pin_verified,
            account_id,
            trading_plan,
            data_plan,
            tax_allowance: None,
            tax_allowance_start: None,
            tax_allowance_end: None,
            optin_order_push,
            optin_order_email,
            country,
            language,
            timezone,
        }
    }
}


