/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Mode : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "paper")]
    Paper,
    #[serde(rename = "money")]
    Money,

}

impl ToString for Mode {
    fn to_string(&self) -> String {
        match self {
            Self::Paper => String::from("paper"),
            Self::Money => String::from("money"),
        }
    }
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Paper
    }
}




