/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlaybookGlobalsModelsSchemaOrderTypes : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlaybookGlobalsModelsSchemaOrderTypes {
    #[serde(rename = "market")]
    Market,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "stop_limit")]
    StopLimit,

}

impl ToString for PlaybookGlobalsModelsSchemaOrderTypes {
    fn to_string(&self) -> String {
        match self {
            Self::Market => String::from("market"),
            Self::Stop => String::from("stop"),
            Self::Limit => String::from("limit"),
            Self::StopLimit => String::from("stop_limit"),
        }
    }
}

impl Default for PlaybookGlobalsModelsSchemaOrderTypes {
    fn default() -> PlaybookGlobalsModelsSchemaOrderTypes {
        Self::Market
    }
}




