/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Portfolio {
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "isin_title")]
    pub isin_title: String,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "buy_price_avg")]
    pub buy_price_avg: i32,
    #[serde(rename = "estimated_price_total", skip_serializing_if = "Option::is_none")]
    pub estimated_price_total: Option<i32>,
    #[serde(rename = "estimated_price", skip_serializing_if = "Option::is_none")]
    pub estimated_price: Option<i32>,
}

impl Portfolio {
    pub fn new(isin: String, isin_title: String, quantity: i32, buy_price_avg: i32) -> Portfolio {
        Portfolio {
            isin,
            isin_title,
            quantity,
            buy_price_avg,
            estimated_price_total: None,
            estimated_price: None,
        }
    }
}


