/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PositionType : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositionType {
    #[serde(rename = "order_buy")]
    OrderBuy,
    #[serde(rename = "order_sell")]
    OrderSell,
    #[serde(rename = "split")]
    Split,
    #[serde(rename = "import")]
    Import,
    #[serde(rename = "snx")]
    Snx,

}

impl ToString for PositionType {
    fn to_string(&self) -> String {
        match self {
            Self::OrderBuy => String::from("order_buy"),
            Self::OrderSell => String::from("order_sell"),
            Self::Split => String::from("split"),
            Self::Import => String::from("import"),
            Self::Snx => String::from("snx"),
        }
    }
}

impl Default for PositionType {
    fn default() -> PositionType {
        Self::OrderBuy
    }
}




