/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PositionProfit {
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "isin_title")]
    pub isin_title: String,
    #[serde(rename = "profit")]
    pub profit: i32,
    #[serde(rename = "loss")]
    pub loss: i32,
    #[serde(rename = "quantity_bought")]
    pub quantity_bought: i32,
    #[serde(rename = "quantity_sold")]
    pub quantity_sold: i32,
    #[serde(rename = "quantity_open")]
    pub quantity_open: i32,
    #[serde(rename = "opened_at", skip_serializing_if = "Option::is_none")]
    pub opened_at: Option<String>,
    #[serde(rename = "closed_at", skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<String>,
    #[serde(rename = "fees")]
    pub fees: i32,
}

impl PositionProfit {
    pub fn new(isin: String, isin_title: String, profit: i32, loss: i32, quantity_bought: i32, quantity_sold: i32, quantity_open: i32, fees: i32) -> PositionProfit {
        PositionProfit {
            isin,
            isin_title,
            profit,
            loss,
            quantity_bought,
            quantity_sold,
            quantity_open,
            opened_at: None,
            closed_at: None,
            fees,
        }
    }
}


