/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Sides : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sides {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,

}

impl ToString for Sides {
    fn to_string(&self) -> String {
        match self {
            Self::Buy => String::from("buy"),
            Self::Sell => String::from("sell"),
        }
    }
}

impl Default for Sides {
    fn default() -> Sides {
        Self::Buy
    }
}




