/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAccountModel {
    #[serde(rename = "address_street", skip_serializing_if = "Option::is_none")]
    pub address_street: Option<String>,
    #[serde(rename = "address_street_number", skip_serializing_if = "Option::is_none")]
    pub address_street_number: Option<String>,
    #[serde(rename = "address_city", skip_serializing_if = "Option::is_none")]
    pub address_city: Option<String>,
    #[serde(rename = "address_postal_code", skip_serializing_if = "Option::is_none")]
    pub address_postal_code: Option<String>,
    #[serde(rename = "address_country", skip_serializing_if = "Option::is_none")]
    pub address_country: Option<String>,
}

impl UpdateAccountModel {
    pub fn new() -> UpdateAccountModel {
        UpdateAccountModel {
            address_street: None,
            address_street_number: None,
            address_city: None,
            address_postal_code: None,
            address_country: None,
        }
    }
}


