/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Venue : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Venue {
    #[serde(rename = "xmun")]
    Xmun,
    #[serde(rename = "allday")]
    Allday,

}

impl ToString for Venue {
    fn to_string(&self) -> String {
        match self {
            Self::Xmun => String::from("xmun"),
            Self::Allday => String::from("allday"),
        }
    }
}

impl Default for Venue {
    fn default() -> Venue {
        Self::Xmun
    }
}




