/*
 * lemon.markets | Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: b996d5fa9acbe1796d08c2f8360172c63ac713ad
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WithdrawMoneyRequest {
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "pin", skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    #[serde(rename = "idempotency", skip_serializing_if = "Option::is_none")]
    pub idempotency: Option<String>,
}

impl WithdrawMoneyRequest {
    pub fn new(amount: i32) -> WithdrawMoneyRequest {
        WithdrawMoneyRequest {
            amount,
            pin: None,
            idempotency: None,
        }
    }
}


