/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FromDateAnyOf {
    #[serde(rename = "latest")]
    Latest,

}

impl ToString for FromDateAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::Latest => String::from("latest"),
        }
    }
}

impl Default for FromDateAnyOf {
    fn default() -> FromDateAnyOf {
        Self::Latest
    }
}




