/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Instrument {
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "wkn")]
    pub wkn: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::market_data::models::ModelType,
    #[serde(rename = "venues")]
    pub venues: Vec<crate::market_data::models::VenueSpecificAttrs>,
}

impl Instrument {
    pub fn new(isin: String, wkn: String, name: String, _type: crate::market_data::models::ModelType, venues: Vec<crate::market_data::models::VenueSpecificAttrs>) -> Instrument {
        Instrument {
            isin,
            wkn,
            name,
            title: None,
            symbol: None,
            _type,
            venues,
        }
    }
}


