/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ModelType : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModelType {
    #[serde(rename = "stock")]
    Stock,
    #[serde(rename = "bond")]
    Bond,
    #[serde(rename = "warrant")]
    Warrant,
    #[serde(rename = "fund")]
    Fund,
    #[serde(rename = "etf")]
    Etf,
    #[serde(rename = "etn")]
    Etn,
    #[serde(rename = "etc")]
    Etc,

}

impl ToString for ModelType {
    fn to_string(&self) -> String {
        match self {
            Self::Stock => String::from("stock"),
            Self::Bond => String::from("bond"),
            Self::Warrant => String::from("warrant"),
            Self::Fund => String::from("fund"),
            Self::Etf => String::from("etf"),
            Self::Etn => String::from("etn"),
            Self::Etc => String::from("etc"),
        }
    }
}

impl Default for ModelType {
    fn default() -> ModelType {
        Self::Stock
    }
}




