/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OhlcInt {
    #[serde(rename = "isin")]
    pub isin: String,
    #[serde(rename = "o")]
    pub o: i32,
    #[serde(rename = "h")]
    pub h: i32,
    #[serde(rename = "l")]
    pub l: i32,
    #[serde(rename = "c")]
    pub c: i32,
    #[serde(rename = "v")]
    pub v: i32,
    #[serde(rename = "pbv")]
    pub pbv: i32,
    #[serde(rename = "t")]
    pub t: Box<String>,
    #[serde(rename = "mic")]
    pub mic: String,
}

impl OhlcInt {
    pub fn new(isin: String, o: i32, h: i32, l: i32, c: i32, v: i32, pbv: i32, t: String, mic: String) -> OhlcInt {
        OhlcInt {
            isin,
            o,
            h,
            l,
            c,
            v,
            pbv,
            t: Box::new(t),
            mic,
        }
    }
}


