/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseError {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "error_code")]
    pub error_code: String,
    #[serde(rename = "error_message")]
    pub error_message: String,
}

impl ResponseError {
    pub fn new(error_code: String, error_message: String) -> ResponseError {
        ResponseError {
            time: None,
            error_code,
            error_message,
        }
    }
}


