/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VenueSpecificAttrs {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "mic")]
    pub mic: String,
    #[serde(rename = "is_open")]
    pub is_open: bool,
    #[serde(rename = "tradable")]
    pub tradable: bool,
    #[serde(rename = "currency")]
    pub currency: String,
}

impl VenueSpecificAttrs {
    pub fn new(name: String, title: String, mic: String, is_open: bool, tradable: bool, currency: String) -> VenueSpecificAttrs {
        VenueSpecificAttrs {
            name,
            title,
            mic,
            is_open,
            tradable,
            currency,
        }
    }
}


