/*
 * lemon.markets | Historical Market Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1da2ed0b5fefcf155fa143ba4b81c08c3c1c351c
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Venue {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "mic")]
    pub mic: String,
    #[serde(rename = "is_open")]
    pub is_open: bool,
    #[serde(rename = "opening_hours")]
    pub opening_hours: Box<crate::market_data::models::OpeningHours>,
    #[serde(rename = "opening_days")]
    pub opening_days: Vec<String>,
}

impl Venue {
    pub fn new(name: String, title: String, mic: String, is_open: bool, opening_hours: crate::market_data::models::OpeningHours, opening_days: Vec<String>) -> Venue {
        Venue {
            name,
            title,
            mic,
            is_open,
            opening_hours: Box::new(opening_hours),
            opening_days,
        }
    }
}


